name: Conda_SkillsFactory
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  # Core Python & environment
  - python=3.13.5
  - pip
  - setuptools
  - wheel

  # Data manipulation & analysis
  - pandas=2.2.3
  - numpy=2.3.1
  - scipy=1.16.0
  - bottleneck
  - numexpr
  - statsmodels
  - patsy

  # Visualization
  - matplotlib-base
  - seaborn
  - plotly  # via pip: kaleido for export
  - adjusttext

  # Graph/network analysis
  - networkx
  - python-louvain

  # SQL & DB connectivity
  - sqlalchemy
  - psycopg2
  - sqlite

  # Jupyter & IPython
  - ipython
  - jupyter_core
  - matplotlib-inline
  - prompt-toolkit
  - traitlets
  - pygments

  # Parsing & formatting
  - xmltodict
  - lxml
  - orjson
  - simplejson
  - python-dateutil
  - pytz
  - python-tzdata

  # Environment & styling
  - jupyterthemes
  - lesscpy
  - colorama

  # System & compression
  - zlib
  - xz
  - bzip2
  - lz4-c
  - libdeflate
  - openssl
  - ca-certificates

  # Optional: remove low-level system packages unless needed
  # (e.g. libpng, libtiff, libxml2, vc14_runtime, etc.)

  # Pip-only packages
  - pip:
      - kaleido
      - pyvis
      - selenium
      - pytest
      - pytest-timeout
      - python-dotenv
      - tvdatafeed